### ISSUE TITLE
no google chrome store anymore

### ISSUE THREAD

**Issue by Goten87** [daftano/chrome-export-cookie#7]
think the project is down atm if i press the link to download it cannot find the page on the store

**Comment by BlohoJo** [comment]
The last version published on the Chrome store is 1.14.1, which is later than the version published here (1.9).

Here's a Google Drive link to the 1.14.1 version:
https://drive.google.com/file/d/1C3Qoh2R_-xKM_iBEx3aBhbpQNJW7C2m1

You'll have to enable developer mode and load it as an unpacked extension.

**Comment by Ahmed-Soudi** [comment]
thx

**Comment by MewX** [comment]
Thanks! I just noticed it was not synced any more on my new device.

**Comment by nicolaasjan** [comment]
@daftano 
Why has v1.14.1 been removed from the Chrome WebStore?
I sure hope it was not malicious...

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
> @daftano
> Why has v1.14.1 been removed from the Chrome WebStore?
> I sure hope it was not malicious...

It's IS malicious! The compiled extension from Chrome WebStore is very different. You can check the code yourself at `C:\Users\admin\AppData\Local\Google\Chrome\User Data\Default\Extensions\njabckikapfpffapmjgojcnbfjonfjfg`.

**Comment by daftano** [comment]
Google asked to make a change a permission required by the extension to work. I refactored the extension to remove that but their automatic check didn’t pass (despite doing what they asked).
I’m reviewing the extension but didn’t have much time to spend on it.
